<a href="https://colab.research.google.com/github/antonyseba/Enhanced-Feature-Selection-Strategy-/blob/main/FSTopsis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
%pip install skfeature-chappers

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 66.3/66.3 kB 2.0 MB/s eta 0:00:00


In [ ]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score, precision_score, f1_score, recall_score
from sklearn.ensemble import VotingClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.ensemble import VotingClassifier
from sklearn import model_selection
from sklearn.metrics import confusion_matrix
from sklearn. preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import AdaBoostClassifier
#from mlxtend.evaluate import bias_variance_decomp

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
pwd

'/content'

In [ ]:
cd /content/drive/MyDrive/Dataset

/content/drive/MyDrive/Dataset


In [ ]:
!pwd

/content


In [ ]:
dataset = pd.read_csv("Training5.csv")



In [ ]:
dataset.shape

(277, 29)

In [ ]:
pd.set_option('display.max_rows', dataset.shape[0]+1)


In [ ]:
dataset.drop(columns=['ID'],axis=0,inplace=True)

In [ ]:
dataset.shape

(277, 28)

In [ ]:
dataset.columns

Index(['ID', 'cad', 'htn', 'dm', 'pcc', 'ba', 'ane', 'appet', 'pe', 'sod',
       'pot', 'age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'bgr', 'bu', 'sc',
       'hemo', 'pcv', 'wc', 'rc', 'gender', 'race', 'gfr', 'class'],
      dtype='object')

In [ ]:
from sklearn.preprocessing import PowerTransformer
data = dataset.values
# perform a box-cox transform of the dataset
pt = PowerTransformer(method='yeo-johnson')
dataset = pd.DataFrame(pt.fit_transform(data))
#dataset=pd.DataFrame(dataset,columns = ['cad', 'htn', ' dm', 'pcc', 'ba', 'ane', 'appet', 'pe', 'sod','pot', 'age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'bgr', 'bu', 'sc','hemo', 'pcv', 'wc', 'rc', 'gender', 'race', 'gfr', 'class'])



In [ ]:
from sklearn.preprocessing import PowerTransformer
data = datatest.values
# perform a box-cox transform of the dataset
pt = PowerTransformer(method='yeo-johnson')
datatest = pd.DataFrame(pt.fit_transform(data))

NameError: name 'datatest' is not defined

In [ ]:
dataset=dataset.rename(columns={0: "cad", 1: "htn",2: "dm", 3: "pcc",4: "ba", 5: "ane",6: "appet", 7: "pe",8:"sod",9:"pot",10:"age",11:"bp",12: "sg",13: "al", 14: "su",15: "rbc", 16: "pc",17:"bgr",18:"bu",19:"sc",20:"hemo",21:"pcv",22:"wc",23:"rc",24: "gender", 25: "race",26:"gfr",27:"class"})



In [ ]:
datatest=datatest.rename(columns={0:'dm', 1:'bu',2: 'sc',3: 'age',4: 'sg',5: 'al',6: 'hemo',7: 'pcv', 8:'rc',9: 'gfr',10: 'class'})

NameError: name 'datatest' is not defined

In [ ]:
pd.set_option('display.max_rows', dataset.shape[0]+1)
dataset


In [ ]:
data=dataset.copy(deep=True)

In [ ]:
data.shape

(277, 28)

In [ ]:
from numpy.random import seed
from numpy.random import randn
from scipy.stats import shapiro
# seed the random number generator
seed(1)

In [ ]:
dataset.columns

Index(['cad', 'htn', 'dm', 'pcc', 'ba', 'ane', 'appet', 'pe', 'sod', 'pot',
       'age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'bgr', 'bu', 'sc', 'hemo',
       'pcv', 'wc', 'rc', 'gender', 'race', 'gfr', 'class'],
      dtype='object')

In [ ]:

# 1.Feature Selection- ETC
from sklearn.ensemble import ExtraTreesClassifier
# load data

array = dataset.values
XX = dataset.iloc[:,0:27]
#YY = dataset.iloc[:,27]
YY = dataset.iloc[:,27].astype(int)
#YY=y_train
# feature extraction
model = ExtraTreesClassifier(n_estimators=10)
model.fit(XX, YY)
print(model.feature_importances_)

[0.00553649 0.02680779 0.01312766 0.00405245 0.00544484 0.02626549
 0.0076276  0.00961346 0.02258779 0.01343876 0.0586353  0.02522979
 0.01284789 0.0135957  0.01065889 0.02255317 0.00705242 0.03046814
 0.06432379 0.24386413 0.02744098 0.02233478 0.02012162 0.01935206
 0.03340381 0.01351461 0.24010058]


In [ ]:
!pip install shap
import shap

In [ ]:
explainer = shap.Explainer(model, X_train)
shap_values = explainer(X_test)

NameError: name 'X_train' is not defined

In [ ]:
shap.summary_plot(shap_values, X_test)

In [ ]:
# 1.Feature Selection- ETC
from sklearn.ensemble import ExtraTreesClassifier
# load data

#array = dataset.values
XX = dataset.iloc[:,1:28]
YY = dataset.iloc[:,28]
#YY=y_train
# feature extraction
model = ExtraTreesClassifier(n_estimators=10)
model.fit(XX, YY)
print(model.feature_importances_)

[0.0074687  0.03563156 0.03740254 0.01051389 0.00907649 0.01977365
 0.01284817 0.00768842 0.02325821 0.0219075  0.04395406 0.02637214
 0.02700226 0.01996372 0.00848022 0.01729744 0.01282881 0.03951929
 0.06938417 0.16967574 0.04400687 0.02405853 0.02545935 0.02359341
 0.03014442 0.01746492 0.21522552]


In [ ]:
# 2.Feature Selection-Fisher score
from skfeature.function.similarity_based import fisher_score

ranks=fisher_score.fisher_score(XX,YY,mode='rank')
print(ranks)

/usr/local/lib/python3.7/dist-packages/skfeature/utility/construct_W.py:194: FutureWarning: Support for multi-dimensional indexing (e.g. `obj[:, None]`) is deprecated and will be removed in a future version.  Convert to a numpy array before indexing instead.
  class_idx_all = (class_idx[:, np.newaxis] & class_idx[np.newaxis, :])
/usr/local/lib/python3.7/dist-packages/skfeature/utility/construct_W.py:194: FutureWarning: Support for multi-dimensional indexing (e.g. `obj[:, None]`) is deprecated and will be removed in a future version.  Convert to a numpy array before indexing instead.
  class_idx_all = (class_idx[:, np.newaxis] & class_idx[np.newaxis, :])
/usr/local/lib/python3.7/dist-packages/skfeature/utility/construct_W.py:194: FutureWarning: Support for multi-dimensional indexing (e.g. `obj[:, None]`) is deprecated and will be removed in a future version.  Convert to a numpy array before indexing instead.
  class_idx_all = (class_idx[:, np.newaxis] & class_idx[np.newaxis, :])
/usr/lo

ValueError: ignored

In [ ]:
from sklearn.feature_selection import SelectFpr, chi2
X_new = SelectFpr(chi2, alpha=0.01).fit_transform(XX, YY)
X_new.getfield()

NameError: ignored

In [ ]:
# # 3.Feature Selection-ANOVA
#feature extraction - univariate
from numpy import set_printoptions
from sklearn.feature_selection import SelectKBest
from sklearn.feature_selection import f_classif
from sklearn.feature_selection import chi2
test = SelectKBest(score_func=chi2, k=5)
fit = test.fit(XX, YY)
# summarize scores
set_printoptions(precision=3)
print(fit.scores_)
features = fit.transform(XX)
# summarize selected features
print(features[0:10,:])

[2.724e+01 6.868e+01 4.291e+01 2.746e+01 1.174e+01 5.244e+01 1.009e+01
 1.834e+01 2.073e+01 8.808e-01 3.820e+02 6.735e+01 1.114e-03 8.782e+01
 3.316e+01 3.495e+00 6.022e+00 1.449e+03 6.743e+03 7.303e+02 6.839e+01
 1.749e+02 6.265e+03 1.299e+01 5.388e+00 2.763e+00 9.928e+03]
[[1.21e+02 2.00e+01 8.00e-01 8.20e+03 1.08e+02]
 [1.37e+02 6.50e+01 3.40e+00 6.90e+03 1.60e+01]
 [3.52e+02 1.37e+02 3.30e+00 5.80e+03 1.50e+01]
 [7.00e+01 1.07e+02 7.20e+00 1.21e+04 7.00e+00]
 [2.19e+02 8.20e+01 3.60e+00 5.60e+03 1.70e+01]
 [8.90e+01 1.90e+01 1.10e+00 1.03e+04 6.90e+01]
 [1.58e+02 8.50e+01 3.20e+00 8.20e+03 1.90e+01]
 [8.30e+01 4.20e+01 1.20e+00 9.30e+03 4.50e+01]
 [1.28e+02 2.08e+02 9.20e+00 1.63e+04 7.00e+00]
 [1.30e+02 3.00e+01 1.10e+00 7.80e+03 8.90e+01]]


In [ ]:
#feature extraction - univariate
from numpy import set_printoptions
from sklearn.feature_selection import SelectKBest
from sklearn.feature_selection import f_classif
from sklearn.feature_selection import chi2
from sklearn.feature_selection import mutual_info_classif
test = SelectKBest(score_func=mutual_info_classif, k=5)
fit = test.fit(XX, YY)
# summarize scores
set_printoptions(precision=10)
print(fit.scores_)
features = fit.transform(XX)
# summarize selected features
print(features[0:10,:])

[4.4735740474e-02 1.9154453256e-01 1.9173441689e-01 6.9856525114e-02
 0.0000000000e+00 8.8259856972e-02 9.1006833609e-02 2.4336658437e-02
 1.6274718753e-01 1.1858093973e-01 1.1666211973e-01 1.0818616223e-01
 3.8133194529e-02 1.4727825101e-01 8.9257463610e-02 1.2591939456e-01
 1.2970320634e-01 1.5166277398e-01 4.8879017442e-01 1.0350677129e+00
 3.4803015027e-01 2.4848843781e-01 4.4250891738e-04 3.0407817727e-01
 0.0000000000e+00 0.0000000000e+00 1.4754259291e+00]
[[ 20.    0.8  10.9   4.8 108. ]
 [ 65.    3.4   9.7   2.5  16. ]
 [137.    3.3  11.3   3.6  15. ]
 [107.    7.2   9.5   3.7   7. ]
 [ 82.    3.6  10.4   3.6  17. ]
 [ 19.    1.1  15.    4.8  69. ]
 [ 85.    3.2  10.1   4.8  19. ]
 [ 42.    1.2  16.2   5.4  45. ]
 [208.    9.2   8.2   2.7   7. ]
 [ 30.    1.1  15.9   4.5  89. ]]


In [ ]:
#Mean Decrease Accuracy RF
from sklearn.model_selection import cross_val_score

scores = []
clf = RandomForestClassifier()
score_normal = np.mean(cross_val_score(clf, XX, YY, cv = 10))

# X_shuffled = X.copy()
# np.random.shuffle(X_shuffled[X.columns[i]])

# X_shuffled.meanfreq
for i in range(27):
    X_shuffled = XX.copy()
    scores_shuffle = []
    for j in range(3):
        np.random.seed(j*3)
        np.random.shuffle(X_shuffled[XX.columns[i]])
        score = np.mean(cross_val_score(clf, X_shuffled, YY, cv = 10))
        scores_shuffle.append(score)

    scores.append((score_normal - np.mean(scores_shuffle), XX.columns[i]))


In [ ]:
from sklearn.linear_model import RandomizedLogisticRegression

clf = RandomizedLogisticRegression()
clf.fit(XX,YY)
zero_feat = []
nonzero_feat = []
# type(clf.coef_)
for i in range(num_features):
    coef = clf.scores_[i]
    if coef == 0:
        zero_feat.append(XX.columns[i])
    else:
        nonzero_feat.append((coef, XX.columns[i]))

print ('Features that have coeffcient of 0 are: ', zero_feat)
print ('Features that have non-zero coefficients are:')
print (sorted(nonzero_feat, reverse = True))

ImportError: ignored

In [ ]:
data = [1,2,2,3,3,3]

pd_series = pd.Series(data)
counts = pd_series.value_counts()
entropy = entropy(counts)

print(entropy)

NameError: ignored

In [ ]:
# 4.Feature Selection-RFE(multinomial)
from sklearn.feature_selection import RFE
from sklearn.linear_model import LogisticRegression
model = LogisticRegression(solver='lbfgs',multi_class='multinomial',max_iter=100)
rfe = RFE(model)
#pipe = make_pipeline(StandardScaler(), LogisticRegression(solver='lbfgs',multi_class='multinomial',max_iter=100))
fit = rfe.fit(XX, YY)
print("Num Features: %d" % fit.n_features_)
print("Selected Features: %s" % fit.support_)
print("Feature Ranking: %s" % fit.ranking_)
importance = rfe.estimator_.coef_[0]
# summarize feature importance
for i,v in enumerate(importance):
	print('Feature: %0d, Score: %.5f' % (i,v))
# plot feature importance

#plt.bar([x for x in range(len(importance))], importance)
#plt.show()

/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_logistic.py:818: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG,
/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_logistic.py:818: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression


Num Features: 13
Selected Features: [False  True False False False False False False  True  True  True  True
 False  True False  True False False  True  True  True  True False  True
 False False  True]
Feature Ranking: [12  1  4  9 14 10  2 11  1  1  1  1 15  1  3  1  6  5  1  1  1  1  7  1
  8 13  1]
Feature: 0, Score: -0.00210
Feature: 1, Score: -0.06919
Feature: 2, Score: -0.05123
Feature: 3, Score: -0.22261
Feature: 4, Score: -0.13512
Feature: 5, Score: -0.08155
Feature: 6, Score: 0.01478
Feature: 7, Score: -0.06122
Feature: 8, Score: -0.03416
Feature: 9, Score: -0.01656
Feature: 10, Score: -0.00378
Feature: 11, Score: 0.06163
Feature: 12, Score: 0.98506


/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_logistic.py:818: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG,
/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_logistic.py:818: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression


In [ ]:
# 4.Feature Selection-ETC(entropy)
model = ExtraTreesClassifier(n_estimators=10,criterion='entropy')
model.fit(XX, YY)
print(model.feature_importances_)

[0.00377668 0.04431098 0.03941471 0.0184582  0.00476626 0.01579953
 0.02527455 0.00953418 0.02209517 0.01608973 0.03936753 0.02609901
 0.01866527 0.01348616 0.0092063  0.01296684 0.00835477 0.02853905
 0.05399281 0.10074101 0.02753358 0.02657629 0.02323104 0.0419223
 0.02813086 0.01288739 0.3287798 ]


In [ ]:
# 5.Feature Selection-ETC(gini) default
model = ExtraTreesClassifier(n_estimators=10,criterion='gini')
model.fit(XX, YY)
print(model.feature_importances_)

[0.00745684 0.0401288  0.03143325 0.01196785 0.00573886 0.01443198
 0.01614939 0.01073098 0.02694226 0.02714114 0.03472762 0.02959202
 0.01922797 0.02299768 0.00802982 0.01376198 0.01221929 0.0338737
 0.07075592 0.16753029 0.04800106 0.03511291 0.02967359 0.02395159
 0.03454696 0.02254411 0.20133217]


In [ ]:
# 6.Feature Selection-PCA
from sklearn.decomposition import PCA
# feature extraction
pca = PCA(n_components=3)
fit = pca.fit(XX)
# summarize components
print("Explained Variance: %s" % fit.explained_variance_ratio_)
print(fit.components_)

Explained Variance: [9.98003290e-01 1.09394263e-03 6.11025851e-04]
[[-2.19255919e-06  1.37129430e-05  1.71272256e-05  1.08049646e-05
   9.97696914e-06  1.72974798e-06 -1.80660591e-05  2.18063818e-05
  -3.55909750e-05 -2.87111239e-05  2.86538404e-04  4.78679727e-04
  -3.27961654e-07  8.50740767e-05  4.79571251e-05 -9.36814634e-07
  -1.12981640e-05  2.26661716e-03 -3.23866088e-04 -2.62893655e-05
  -9.91825272e-05 -4.53231854e-04  9.99996108e-01 -3.29561646e-05
   5.96991216e-06 -2.61425003e-05 -1.41368211e-03]
 [ 1.15435443e-03  2.75122120e-03  3.21529335e-03  8.13945924e-04
   1.77101568e-04  9.20280464e-04 -1.07332977e-03  5.63384729e-04
  -2.56683665e-02  3.15118408e-04  7.18324774e-02  3.91573515e-02
  -2.08577345e-05  5.04965735e-03  7.84586588e-03 -4.97021660e-04
  -1.40422464e-03  9.25527320e-01  1.58900120e-01  1.07897866e-02
  -1.16761798e-02 -3.48621482e-02 -2.57149569e-03 -3.14573532e-03
  -1.47262324e-04 -2.36501294e-04 -3.30456548e-01]
 [ 6.91457776e-04  3.03926267e-03  1.44

In [ ]:
from sklearn.feature_selection import mutual_info_classif
from pandas import DataFrame
importances=mutual_info_classif(XX,YY)
feat_im=pd.Series(importances, pd.DataFrame.columns[0:len(pd.DataFrame.columns)-1])
feat_im

TypeError: ignored

In [ ]:
# step forward feature elimination

from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import r2_score
from mlxtend.feature_selection import SequentialFeatureSelector as SFS
sfs1 = SFS(RandomForestRegressor(), k_features=27, forward=True,  floating=False, verbose=2,scoring='r2',cv=3)

sfs1 = sfs1.fit(np.array(XX), YY)


[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.4s remaining:    0.0s
[Parallel(n_jobs=1)]: Done  27 out of  27 | elapsed:   10.1s finished

[2021-07-11 16:54:20] Features: 1/27 -- score: 0.9489808522458382[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.4s remaining:    0.0s
[Parallel(n_jobs=1)]: Done  26 out of  26 | elapsed:    9.9s finished

[2021-07-11 16:54:30] Features: 2/27 -- score: 0.9604319109347602[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.4s remaining:    0.0s
[Parallel(n_jobs=1)]: Done  25 out of  25 | elapsed:    9.6s finished

[2021-07-11 16:54:40] Features: 3/27 -- score: 0.9629407582100357[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done  

In [ ]:
sfs1.k_feature_idx_

(0,
 1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 11,
 12,
 13,
 14,
 15,
 16,
 17,
 18,
 19,
 20,
 21,
 22,
 23,
 24,
 25,
 26)

In [ ]:
XX.columns[list(sfs1.k_feature_idx_)]

Index(['cad', 'htn', 'dm', 'pcc', 'ba', 'ane', 'appet', 'pe', 'sod', 'pot',
       'age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'bgr', 'bu', 'sc', 'hemo',
       'pcv', 'wc', 'rc', 'gender', 'race', 'gfr'],
      dtype='object')

In [ ]:
# step backward feature elimination

sfs1 = SFS(RandomForestRegressor(), k_features=1,  forward=False, floating=False, verbose=2, scoring='r2', cv=3)

sfs1 = sfs1.fit(np.array(XX), YY)

[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.5s remaining:    0.0s
[Parallel(n_jobs=1)]: Done  27 out of  27 | elapsed:   12.8s finished

[2021-07-11 17:10:28] Features: 26/1 -- score: 0.9650960107819703[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.5s remaining:    0.0s
[Parallel(n_jobs=1)]: Done  26 out of  26 | elapsed:   12.2s finished

[2021-07-11 17:10:40] Features: 25/1 -- score: 0.9638556657334831[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.5s remaining:    0.0s
[Parallel(n_jobs=1)]: Done  25 out of  25 | elapsed:   11.6s finished

[2021-07-11 17:10:52] Features: 24/1 -- score: 0.9645539410432625[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done  

In [ ]:
model = LogisticRegression()
rfe = RFE(model, 1)
fit = rfe.fit(XX, YY)
print("Num Features: %s" % (fit.n_features_))
print("Selected Features: %s" % (fit.support_))
print("Feature Ranking: %s" % (fit.ranking_))

/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)
/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression


Num Features: 1
Selected Features: [False False False False False False False False False False False False
 False False False False False False False  True False False False False
 False False False]
Feature Ranking: [24 10 16 21 26 22 14 23  6 11  3  4 27  7 15 13 18 17 12  1  8  5 19  9
 20 25  2]


/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)
/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression


In [ ]:
sfs1.k_feature_idx_

(0,
 1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 11,
 12,
 13,
 14,
 15,
 16,
 17,
 18,
 19,
 20,
 21,
 22,
 23,
 24,
 25,
 26)

In [ ]:
XX.columns[list(sfs1.k_feature_idx_)]

Index(['cad', 'htn', 'dm', 'pcc', 'ba', 'ane', 'appet', 'pe', 'sod', 'pot',
       'age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'bgr', 'bu', 'sc', 'hemo',
       'pcv', 'wc', 'rc', 'gender', 'race', 'gfr'],
      dtype='object')

In [ ]:
from sklearn.linear_model import Lasso
from sklearn.feature_selection import SelectFromModel
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
scaler.fit(XX.fillna(0))
sel_ = SelectFromModel(Lasso(alpha=100))
sel_.fit(scaler.transform(XX.fillna(0)), YY)
sel_.get_support()

array([False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False])

In [ ]:
selected_feat = XX[(sel_.get_support())]

print('total features: {}'.format((XX.shape[1])))
print('selected features: {}'.format(len(selected_feat)))
print('features with coefficients shrank to zero: {}'.format(
    np.sum(sel_.estimator_.coef_ == 0)))

ValueError: ignored